### ISSUE TITLE
The /projects/:id/fundings path indexes all available fundings

### ISSUE THREAD

**Issue by kleyv** [kleyv/airbnb-falcony#26]
We need to figure out where the correct route to list all fundings a specific investor @raffoz @Flott2410 @Tiago-Palhoca

**Comment by Flott2410** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Power ups explanation](https://trello.com/c/0kBc0kO3/23-power-ups-explanation)

**Comment by kleyv** [comment]
Solved with https://github.com/kleyv/airbnb-falcony/pull/34
